name: Java Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check Java
        run: java -version

      - name: Check Maven
        run: mvn -version

      - name: Build Project
        run: mvn clean compile