name: Fortify SAST Scan

on:
  push:
    branches:
      - main

jobs:
  fortify-scan:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verify Java
        run: java -version

      - name: Verify Maven
        run: mvn -version

      - name: Fortify Clean
        run: sourceanalyzer -b fortify-demo -clean

      - name: Fortify Translate
        run: sourceanalyzer -b fortify-demo mvn clean compile

      - name: Fortify Scan
        run: sourceanalyzer -b fortify-demo -scan -f fortify-demo.fpr